In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime
import mplfinance as mpf
from fast_ewma import _ewma

ImportError: cannot import name '_ewma' from 'fast_ewma' (c:\Users\outof\Desktop\afml\fast_ewma.py)

In [6]:
def signed_tick(tick, initial_value=1.0):
    diff = tick['priceclose'] - tick['priceclose'].shift(1)
    return (abs(diff) / diff).ffill().fillna(initial_value)

In [10]:
df = pd.read_csv("Future_tick_101T3.csv")
df = df[df['logdate'] >= 20221218]
df = df.drop(['Unnamed: 0'],axis=1)

In [11]:
df['signed_tick'] = signed_tick(df)
df.iloc[50:60]

,logdate,logtime,stockcode,priceopen,pricehigh,pricelow,priceclose,volume,signed_tick
50,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,1,1.0
51,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,26,1.0
52,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,1,1.0
53,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,1,1.0
54,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,1,1.0
55,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,1,1.0
56,20221220,1415,101T3,302.049988,302.049988,302.049988,302.049988,1,1.0
57,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,1,-1.0
58,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,1,-1.0
59,20221220,1415,101T3,302.000000,302.000000,302.000000,302.000000,28,-1.0